version: '3.1'
services:
    phjulian:
        build:
            context: .
            dockerfile: Dockerfile-phjulian
        restart: unless-stopped
        ports:
            - '3100:80'
    
    blick:
        build:
            context: .
            dockerfile: Dockerfile-blick
        restart: unless-stopped
        ports:
            - '3101:80'